### PR TITLE
need flying machine for video but 2 for 1 baloon?

### PR DESCRIPTION
**Pull request by realovee**
please, i need version with more blocks for 1 baloon. I cant use programmers programs, and i trying but i cant do this alone :C

### CODE REVIEW

**Comment by Pfahli** [comment]
You don't need to change the source code and make a patch for this, theres a dedicates configuration file for that.

Just go to the path:

`config/PlatosTransporters/config.acfg`

You will find the following content:

```#should vehicle material use a whitelist? (default: false)
whitelist=false
#amount of blocks 1 Airship Balloon can lift (default: 2)
balloon=2
#amount of blocks 1 Water Float can lift (default: 20)
float=20
#amount of blocks 1 wheel can lift (default: 10)
wheel=10
#speed of vehicles on their correct terrain (default: 0.2)
cspeed=0.2
#speed of vehicles when not on their correct terrain (default: 0.05)
nspeed=0.05
```

Here you can adjust all the parameters to you liking. In your case, setting balloon = 1000 would be the easiest way.

**Comment by realovee** [comment]
> You don't need to change the source code and make a patch for this, theres a dedicates configuration file for that.
> 
> Just go to the path:
> 
> `config/PlatosTransporters/config.acfg`
> 
> You will find the following content:
> 
> ```
> whitelist=false
> #amount of blocks 1 Airship Balloon can lift (default: 2)
> balloon=2
> #amount of blocks 1 Water Float can lift (default: 20)
> float=20
> #amount of blocks 1 wheel can lift (default: 10)
> wheel=10
> #speed of vehicles on their correct terrain (default: 0.2)
> cspeed=0.2
> #speed of vehicles when not on their correct terrain (default: 0.05)
> nspeed=0.05
> ```
> 
> Here you can adjust all the parameters to you liking. In your case, setting balloon = 1000 would be the easiest way.

where can i found this file? (i must open .jar or somethink?)

**Comment by Pfahli** [comment]
No, its located directly in your server folder. Theres no need to edit the .jar-file.

The path for single player mode is;
`C:\Users\###YOUR LOCAL USERNAME###\AppData\Roaming\.minecraft\config\PlatosTransporters`
You can just click on the "Mods" button in the forge client, then go one folder up in windows explorer and then go to the path mentioned above.

**Comment by realovee** [comment]
ooo i understand now, Thank you!

**Pull request closed without merging**
